version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.0.1
    hostname: kafka
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'

  rest-proxy:
    image: confluentinc/cp-kafka-rest:7.0.1
    container_name: rest-proxy
    depends_on:
      - kafka
    ports:
      - "8082:8082"
    environment:
      KAFKA_REST_HOST_NAME: rest-proxy
      KAFKA_REST_LISTENERS: http://0.0.0.0:8082
      KAFKA_REST_BOOTSTRAP_SERVERS: PLAINTEXT://kafka:9092
      KAFKA_REST_CONSUMER_REQUEST_TIMEOUT_MS: 30000

  kowl:
    image: quay.io/cloudhut/kowl:master
    container_name: kowl
    depends_on:
      - kafka
    ports:
      - "8080:8080"
    environment:
      KAFKA_BROKERS: kafka:9092

  ondutynow:
    build:
      context: ./OnDutyNow
      dockerfile: Dockerfile
    container_name: ondutynow
    ports:
      - "8010:8010"
    volumes:
      - ./OnDutyNow:/var/www/html
    depends_on:
      - rest-proxy
    environment:
      APP_ENV: local
      APP_DEBUG: true
      KAFKA_REST_PROXY_URL: http://rest-proxy:8082
  ondutydoctor:
    build:
      context: ./OnDutyDoctor
      dockerfile: Dockerfile
    container_name: ondutydoctor
    ports:
      - "8011:8011"
    volumes:
      - ./OnDutyDoctor:/var/www/html
    depends_on:
      - kafka
    environment:
      APP_ENV: local
      APP_DEBUG: true
      KAFKA_BROKER: kafka:9092
  onduty-monitor:
    build:
      context: ./OnDutyMonitor
    container_name: ondutymonitor
    ports:
      - "3000:3000"
    environment:
      - KAFKA_BROKER=kafka:9092
      - KAFKA_CLIENT_ID=monitor-client
    depends_on:
      - kafka
  init-topics:
    image: confluentinc/cp-kafka:7.0.1
    depends_on:
      - kafka
    volumes:
      - ./kafka-topics.txt:/topics/kafka-topics.txt
      - ./init-topics.sh:/init-topics.sh
    entrypoint: [ "sh", "/init-topics.sh" ]




